### ISSUE TITLE
Feature Request: Download VOD if there is a failure downloading the stream

### ISSUE THREAD

**Issue by trillex** [EnterGin/Auto-Stream-Recording-Twitch#8]
Love this script, saved me from having to attempt to set something up myself that would have been vastly inferior. 

However, every now and then I seem to get a connection refused from twitch. When this happens, would it be possible for the script to automatically have the VOD downloaded in it's place?

**Comment by EnterGin** [comment]
It's really hard to catch actual failure downloading because there are many situations like this:
![image](https://user-images.githubusercontent.com/51099894/90315256-9f236300-df22-11ea-8b66-0a15796cf3db.png)
Stream is over but there are some errors.
You can toggle ```self.downloadVOD``` to 1 to download VOD after streamlink subprocess finish, but there is another problem accurs. If you had a failure downloading - script will download only part of VOD. Checking every VOD to be finished after errors is possible but unreliable and out of scope because in this case I should make another thread only for it.

**Comment by EnterGin** [comment]
And it would be good if you provide log of such failure download.

**Comment by trillex** [comment]
Sadly don't have any logs, but if it happens again, I'll toss it up. 

I see that you've thought about this extensively, so if you don't see a means to do it right, you can just close this issue.

**Comment by EnterGin** [comment]
If you have any additions - feel free to write again 🙂

**Comment by trillex** [comment]
Log, this is exactly what I saw when it was downloading a live stream - although in this case it is from someone who is just being watched and isn't live at the moment. 

```
Auto Stream Recording Twitch v1.6.0
Configuration:
OS: Windows 10
Root path: C:\\twitch
Ffmpeg path: C:\\scripts
Timezone: Europe/Copenhagen (2.0)
Chat downloading Enabled
VOD downloading Disabled
Checking for dragoxdk every 30.0 seconds. Record with best quality.
[cli][info] Found matching plugin twitch for URL twitch.tv/dragoxdk
[cli][info] Waiting for streams, retrying every 30.0 second(s)
[cli][error] Unable to open URL: https://usher.ttvnw.net/api/channel/hls/dragoxdk.m3u8?player=twitchweb&p=872998&type=any&allow_source=true&allow_audio_only=true&allow_spectre=false&sig=2c4c4f82e07ba1b20238272d847c8630b84fbacf&token=%7B%22adblock%22%3Afalse%2C%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22blackout_enabled%22%3Afalse%2C%22channel%22%3A%22dragoxdk%22%2C%22channel_id%22%3A50786261%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%2C%22view_until%22%3A1924905600%7D%2C%22ci_gb%22%3Afalse%2C%22geoblock_reason%22%3A%22%22%2C%22device_id%22%3Anull%2C%22expires%22%3A1597514387%2C%22extended_history_allowed%22%3Afalse%2C%22game%22%3A%22%22%2C%22hide_ads%22%3Afalse%2C%22https_required%22%3Afalse%2C%22mature%22%3Afalse%2C%22partner%22%3Afalse%2C%22platform%22%3Anull%2C%22player_type%22%3Anull%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22server_ads%22%3Atrue%2C%22show_ads%22%3Atrue%2C%22subscriber%22%3Afalse%2C%22turbo%22%3Afalse%2C%22user_id%22%3Anull%2C%22user_ip%22%3A%2285.203.138.223%22%2C%22version%22%3A2%7D&fast_bread=True (('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
```

**Comment by EnterGin** [comment]
Then streamer is live you will get ```Failed to reload playlist``` warning because playlist is already retrieved.
I tried to implement this error and I get this warning:
```Failed to reload playlist: Unable to open URL: https://video-weaver.arn03.hls.ttvnw.net/v1/playlist/***.m3u8 (HTTPSConnectionPool(host='video-weaver.arn03.hls.ttvnw.net', port=443): Max retries exceeded with url: /v1/playlist/***.m3u8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0519BB70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)))```
Because of this there might be lots of false alarms.

I will take a closer look at this problem later now I can't see versatile and effective way to solve this issue.
